<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>8&nbsp; Linear Regression – Data Analysis and Statistics for Political Science</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./references.html" rel="next">
<link href="./inferential.html" rel="prev">
<link href="./images/favicon.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-427913099b0a9f0709402a55d3c778ba.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./linreg1.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Linear Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Data Analysis and Statistics for Political Science</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About the Author</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rstudio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Using R and RStudio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Research and Data: The Basics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dataorg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Importing and Organization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dataviz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./choropleth.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Choropleth Maps</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inferential.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Inferential Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linreg1.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendixa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Widely-Used Political Science Datasets</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#mechanics-of-regression-analysis" id="toc-mechanics-of-regression-analysis" class="nav-link active" data-scroll-target="#mechanics-of-regression-analysis"><span class="header-section-number">8.1</span> Mechanics of Regression Analysis</a>
  <ul class="collapse">
  <li><a href="#finding-the-line-of-best-fit" id="toc-finding-the-line-of-best-fit" class="nav-link" data-scroll-target="#finding-the-line-of-best-fit"><span class="header-section-number">8.1.1</span> Finding the Line of Best Fit</a></li>
  <li><a href="#summarizing-the-line-of-best-fit" id="toc-summarizing-the-line-of-best-fit" class="nav-link" data-scroll-target="#summarizing-the-line-of-best-fit"><span class="header-section-number">8.1.2</span> Summarizing the Line of Best Fit</a></li>
  <li><a href="#error-variance-goodness-of-fit-r2-and-standard-errors" id="toc-error-variance-goodness-of-fit-r2-and-standard-errors" class="nav-link" data-scroll-target="#error-variance-goodness-of-fit-r2-and-standard-errors"><span class="header-section-number">8.1.3</span> Error Variance, Goodness of Fit (<span class="math inline">\(R^2\)</span>), and Standard Errors</a></li>
  </ul></li>
  <li><a href="#regression-assumptions" id="toc-regression-assumptions" class="nav-link" data-scroll-target="#regression-assumptions"><span class="header-section-number">8.2</span> Regression Assumptions</a>
  <ul class="collapse">
  <li><a href="#linearity-in-the-parameters" id="toc-linearity-in-the-parameters" class="nav-link" data-scroll-target="#linearity-in-the-parameters"><span class="header-section-number">8.2.1</span> Linearity in the Parameters</a></li>
  <li><a href="#observations-are-independent-from-one-another" id="toc-observations-are-independent-from-one-another" class="nav-link" data-scroll-target="#observations-are-independent-from-one-another"><span class="header-section-number">8.2.2</span> Observations are Independent from One Another</a></li>
  <li><a href="#exogeneity" id="toc-exogeneity" class="nav-link" data-scroll-target="#exogeneity"><span class="header-section-number">8.2.3</span> Exogeneity</a></li>
  <li><a href="#residuals-are-white-noise" id="toc-residuals-are-white-noise" class="nav-link" data-scroll-target="#residuals-are-white-noise"><span class="header-section-number">8.2.4</span> Residuals are “White Noise”</a></li>
  <li><a href="#no-perfect-multicollinearity" id="toc-no-perfect-multicollinearity" class="nav-link" data-scroll-target="#no-perfect-multicollinearity"><span class="header-section-number">8.2.5</span> No Perfect Multicollinearity</a></li>
  </ul></li>
  <li><a href="#simple-regression-estimation-and-interpretation" id="toc-simple-regression-estimation-and-interpretation" class="nav-link" data-scroll-target="#simple-regression-estimation-and-interpretation"><span class="header-section-number">8.3</span> Simple Regression: Estimation and Interpretation</a>
  <ul class="collapse">
  <li><a href="#social-media-consumption-and-affective-polarization" id="toc-social-media-consumption-and-affective-polarization" class="nav-link" data-scroll-target="#social-media-consumption-and-affective-polarization"><span class="header-section-number">8.3.1</span> Social Media Consumption and Affective Polarization</a></li>
  <li><a href="#the-effect-of-party-identification-on-supreme-court-approval" id="toc-the-effect-of-party-identification-on-supreme-court-approval" class="nav-link" data-scroll-target="#the-effect-of-party-identification-on-supreme-court-approval"><span class="header-section-number">8.3.2</span> The Effect of Party Identification on Supreme Court Approval</a></li>
  </ul></li>
  <li><a href="#multiple-regression-estimation-and-interpretation" id="toc-multiple-regression-estimation-and-interpretation" class="nav-link" data-scroll-target="#multiple-regression-estimation-and-interpretation"><span class="header-section-number">8.4</span> Multiple Regression: Estimation and Interpretation</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">8.5</span> Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<img src="images/banner.png" style="width: 100%; height: auto; margin-bottom: 20px;">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-reg1" class="quarto-section-identifier"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Linear regression essentially brings together every major theme from the prior chapters. In what is known as “simple regression,” analysts evaluate the relationship between one independent variable, <em>x</em>, and a dependent variable, <em>y</em>. Put another way, regression evaluates the effect of <em>x</em> on <em>y</em>. In “multiple regression,” analysts evaluate <em>the effects of multiple x variables</em> on <em>y</em>. Importantly, regression analysis is capable of evaluating what can be called the “3 S’s” of an effect: (1) <em>sign</em>, or the direction of the effect (positive or negative); (2) the <em>size</em> of the effect, or <em>by how much</em> a given change in <em>x</em> increases <em>y</em>; and (3) <em>statistical significance</em>, or the inference we can make about whether the effect is non-zero in the population.</p>
<p>This chapter will first go through the mechanics of regression analysis: how to find the line of best fit, how to interpret it, and how to transform it into an inferential statistics exercise (using sample statistics and standard errors). Then, the chapter will discuss the assumptions that go into regression analysis, followed by applied examples in both simple regression and multiple regression.</p>
<section id="mechanics-of-regression-analysis" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="mechanics-of-regression-analysis"><span class="header-section-number">8.1</span> Mechanics of Regression Analysis</h2>
<p>At its core, regression possesses an elegance that makes it the most popular mode of statistical analysis for political scientists and social scientists more generally. The mission of regression analysis is straightforward. Consider the following graphs that <a href="dataviz.html" class="quarto-xref"><span>Chapter 4</span></a> (<a href="dataviz.html#sec-bgd" class="quarto-xref"><span>Section 4.3</span></a>) used to visualize the strength of a bivariate relationship between <em>x</em> and <em>y</em>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="linreg1_files/figure-html/slopes-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Recall that the lines that go through the datapoints are called “lines of best fit,” and <code>ggplot</code> can add those in the graph. This line of best is also known as a <em>regression line</em>. It is the line that best fits the data, which here is the relationship (shown via a scatterplot) between <em>x</em> and <em>y</em>. The mission of regression analysis is to: (1) estimate the line of best fit and (2) summarize this line of best fit. For the latter, the critical “sample statistic” that summarizes the relationship is called a “slope estimate.” This estimate measures how much a given change in <em>x</em> “moves” or changes <em>y</em>. <em>The steeper the slope in the graphs above, the larger this slope estimate will be</em>. Consider the top row. The slope estimate would be the largest in graph A, followed by graph B, and then C. In graph A, a given increase in <em>x</em> generates a very large increase in <em>y</em>. In graph B, the same given increase in <em>x</em> generates a much smaller increase in <em>y</em>. Thus, the effect of <em>x</em> on <em>y</em> is much stronger in graph A than B. Graph C shows a “zero” or “null effect.” A given increase in <em>x</em> generates no change in <em>y</em>. Thus a flat slope, like in graph C, indicates a null effect of <em>x</em> on <em>y</em>, or no relationship between <em>x</em> and <em>y</em>.</p>
<p>Graphs D through F show analogous results for a <em>negative</em> effect of <em>x</em> on <em>y</em>. Graph D shows the strongest negative effect, followed by graph E. Graph F shows the same null effect as graph C. In graph D, a given increase in <em>x</em> generates a very large decrease in <em>y</em>. Graph E shows that the same given increase in <em>x</em> generates a smaller decrease in <em>y</em>.</p>
<p>These are the nuts of bolts of regression analysis. After summarizing the direction and size of the relationship, researchers use inferential statistics to evaluate whether the effect is <em>statistically significant</em>. Recall that for any inferential statistics problem, we need a sample statistic and a standard error for that sample statistic. In regression analysis, our sample statistic is the <em>slope estimate</em> representing the effect of <em>x</em> on <em>y</em>. The chapter will discuss the process of generating a standard error for this slope estimate, which allows the researcher to conduct a full hypothesis test of whether that slope is statistically significant, and in particular, whether the estimate is significantly different from 0, or a null effect.</p>
<section id="finding-the-line-of-best-fit" class="level3" data-number="8.1.1">
<h3 data-number="8.1.1" class="anchored" data-anchor-id="finding-the-line-of-best-fit"><span class="header-section-number">8.1.1</span> Finding the Line of Best Fit</h3>
<p>In the graphs above, the line of best fit in each graph “looks right” in that it goes through the middle of the datapoints in the scatterplot. Examine the scatterplot below and visualize the line of best fit.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="linreg1_files/figure-html/lbf1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<p>If you could draw it on the graph, I bet it would almost exactly match the actual line of best fit. This is one of the reasons why regression is so intuitive and elegant — because it closely tracks the data visualization lessons from <a href="dataviz.html" class="quarto-xref"><span>Chapter 4</span></a>.</p>
<p>Now when I include the actual line of best fit below, think about what actually makes this the line of best.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="linreg1_files/figure-html/lbf2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<p>The fact that it cuts directly through the middle of the x-to-y pattern of datapoints actually tells us something about the “misses,” or the errors. The logic is analogous to estimating a mean and standard deviation (<a href="descriptive.html" class="quarto-xref"><span>Chapter 6</span></a>). The mean is the arithmetic middle of the distribution, but standard deviation, as a measure of dispersion, gives us an estimate of how much the datapoints “miss” the mean, or how much variation there is around the mean. But the mean is still our “best guess” for what a typical value would be because it falls at the point where there is “zero error.”</p>
<p>The same thing goes for a regression line of best fit. Think of it as the “average” value of <em>y</em> for a given value of <em>x</em>, while the datapoints that fall away from the regression line represent deviations (“errors”) from the line of best fit. Of course, no regression line is perfect, but we want to capture how well our regression line actually does fit the data. Recall the intuition on this exact point from <a href="dataviz.html" class="quarto-xref"><span>Chapter 4</span></a>:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="linreg1_files/figure-html/lbf3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Graph A shows the highest goodness of fit, followed by graph B then C. The more tightly packed the datapoints are around the regression line, the higher the goodness of fit.</p>
<p>The graph below breaks down what a “miss” or “error” looks like in regression analysis. In the graph, the three dark blue dots represent three of the thousands of light blue datapoints in the scatterplot. The black line of best fit is included in the graph.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="linreg1_files/figure-html/lbf4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<p>The graph conveys three critical pieces of information. First, the blue dots are <strong>observed values</strong>, the naturally occurring value for a particular observation. For example, observation 1 has an <em>x</em> value of just greater than 40 and a <em>y</em> of about 60. The coordinate, then, can be written as: <span class="math inline">\(x_1,~y_1\)</span>. Sometimes you will see coordinates with parentheses around them: <span class="math inline">\((x_1,~y_1)\)</span>. The figure omits those parentheses. Second, the brown dots represent the <strong>predicted values</strong> of <em>y</em> for a given value of <em>x</em>. The notation for a predicted value of <em>y</em> is <span class="math inline">\(\hat{y}\)</span>, which analysts pronounce as “y-hat” (yes, it’s that literal — the caret on top of <em>y</em> looks like a hat). Note that <span class="math inline">\(\hat{y}\)</span> for a given value of <em>x</em> will <em>always be directly on the regression line</em>. Third, the red, vertical lines extending from the predicted values to the observed values are the misses, or errors. In regression analysis, these misses are called either <strong>errors</strong> or <strong>residuals</strong>. The notation for this error is <span class="math inline">\(\hat{u}\)</span>, or “u-hat.” The graph implies that <span class="math inline">\(\hat{u}\)</span> is simply the observed value minus the predicted value, or more formally: <span class="math inline">\(\hat{u}_i=y_i-\hat{y}_i\)</span>, where the subscript <em>i</em> represents a given observation (e.g., observation 1, 2, etc.).</p>
<p>Once we have fit the regression line, like in the figure above, we can use residuals to assess how far off our prediction is from the actual observed value. For observation 1, the graph shows that the observed value misses on the high side of the regression line — a positive residual. For observation 3, the observed value misses the regression line on the low side — a negative residual. Some observations will be very close to the regression line. Observation 2 in the graph is right on the regression line, which means that for this given value of <em>x</em>: <span class="math inline">\(y_i=\hat{y}_i\)</span> <em>and</em> <span class="math inline">\(\hat{u}_i=0\)</span>.</p>
<p>When we are starting from scratch with just a scatterplot of datapoints between <em>y</em> and <em>x</em>, we must ask, <em>where does the line of best fit actually come from</em>? How do we actually get the <em>one</em> line of best fit when there are actually an infinite number of candidates for line of best fit? The graph below illustrates this dilemma and begins to lay down the logic for the regression method known as <strong>ordinary least squares</strong> (or <strong>OLS</strong>). OLS is synonymous with what we commonly call “linear regression analysis.” The “L” in OLS implies that our regression line that best fits the data will be the one that <em>minimizes</em> the total degree of “error, or residuals, from the prior graph. The graph below displays seven possible lines of best fit. Line 5 is the line of best fit, but it is surrounded by other candidates, some of which are plausible candidates and some implausible.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="linreg1_files/figure-html/lbf5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<p>What makes lines 1 and 2 completely implausible? First, their slopes are negative when the scatterplot clearly implies a positive slope. Imagine plotting the observed versus predicted values for these lines like in the prior graph. The degree of error for lines 1 and 2 would be massive. Lines 3 through 7 are all in the right ballpark because each has a positive slope. Line 4 would generate a lower degree of error than line 3. Line 5, which we know is the line of best fit, would generate a lower degree of error than line 4. Line 6 (the long-dashed line) is very similar to line 5, meaning that its total degree of error would be lower than lines 7 or 4.</p>
<p>The intuition in this graph feeds the logic surrounding the “least squares” element of OLS for finding <em>the one</em> line of best. If the line of best fit is the one that minimizes the total degree of error, we need to work with a quantity that represents each candidate line’s “total error.” The quantity that represents this error is called the <strong>sum of squared residuals</strong>, or <strong>SSR</strong>. Remember that a residual, or an “error,” is represented by <span class="math inline">\(\hat{u}=y_i-\hat{y}_i\)</span>. Just like in the equation for variance and standard deviation in <a href="descriptive.html" class="quarto-xref"><span>Chapter 6</span></a>, if we simply added up the errors across all observations, the negative errors that miss below the line would offset the positive errors that fall above the line. Thus, we use the <em>squared residuals</em>, or <span class="math inline">\(\hat{u}_i^2\)</span>, which means that all of the <span class="math inline">\(\hat{u}_i^2\)</span> quantities will be positive. Then, <strong>SSR</strong> — the critical quantity representing the “total error” for each candidate regression line — is represented via the following equation:</p>
<p><span class="math display">\[SSR = \sum\limits_{i=1}^{N}(y_i-\hat{y}_i)^2 = \sum\limits_{i=1}^{N}\hat{u}_i^2\]</span></p>
<p>The central mission in OLS is to <strong>find <em>the one</em> line that minimizes SSR</strong>. This boils down to a calculus problem and the use of “partial differentiation” — taking the partial derivative of SSR with respect to the slope estimate (and other parameters, which I will define below): <span class="math inline">\(\frac{\partial SSR}{\partial \beta}\)</span>.</p>
<p>The graph below shows a visualization for this logic, particularly SSR as a function of the parameters. In this case, I simplify the x-axis and make it the slope of each line from the prior graph (e.g., line 1 is a negative slope, line 3 is close to 0 but positive, and lines 4-7 have positive slopes).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="linreg1_files/figure-html/lbf6-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<p>The graph shows that <em>one and only one regression line minimizes SSR</em>: That is line 5. The graph visualizes the differential calculus problem. In calculus, one solves for the partial derivative and then sets that derivative to 0 (which is the minimum in this case) and finds the slope parameter associated with that particular line. In the graph above, the line of best fit is the one for which the slope of the line tangent to the curve is 0 (which is associated with setting the partial derivative to 0 and solving for the slope). The dashed horizontal line in the graph is this line tangent to the curve when x=1 (line 5). The slope of that line is 0, which means the line associated with that point is the line of best fit — it is <em>the one</em> regression line that minimizes the sum of squared residuals (SSR).</p>
<p>The process of finding the line of best fit follows a well-known formula that was derived over 200 years ago. Retrieving the line of best fit is somewhat computationally intense, though modern statistical packages, like RStudio, can generate regression results in less than a second, meaning that analysts do not need to concern themselves with deriving the line of best fit manually. Once the line of best fit is determined, the task researchers <em>do</em> have to concern themselves with is interpreting the results of the regression. This task begins with summarizing the line of best fit.</p>
</section>
<section id="summarizing-the-line-of-best-fit" class="level3" data-number="8.1.2">
<h3 data-number="8.1.2" class="anchored" data-anchor-id="summarizing-the-line-of-best-fit"><span class="header-section-number">8.1.2</span> Summarizing the Line of Best Fit</h3>
<p>Once we derive the line of best fit, we need to summarize that line, particularly deriving and interpreting the core parameter estimates (or “statistics”). The figure below provides a visual representation for how to interpret a regression line of best fit. Many readers will already have familiarity with this exercise from their high school algebra class and their use of <span class="math inline">\(y=mx+b\)</span>. From that equation, b represented the <strong>y-intercept</strong>, or the point on the regression line where the line intersects with the y-axis. Then, “m” is the <strong>slope</strong>, or “rise over run.” The graph below uses the exact same logic but different notation. After describing this figure, I will then outline the regression equations in sample and population form.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="linreg1_files/figure-html/regparts-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<p>First, in any graph, the point at which <em>x</em>=0 and <em>y</em>=0 is called the <strong>origin</strong>. In this graph, the line of best fit does not run through the origin, of course. As discussed above, the point at which the line of best fit intersects with the y-axis is called the y-intercept. The y-intercept is the predicted value of <em>y</em> (i.e., since it is a point on the regression line) when <em>x</em>=0. In regression analysis, the y-intercept is denoted as <span class="math inline">\(\hat\beta_0\)</span>. It is one of the two parameter estimates in a “simple regression” equation, i.e., with just one independent variable, <em>x</em>. It gets a “hat” because I treat it as a sample estimate instead of a population parameter (via <a href="inferential.html" class="quarto-xref"><span>Chapter 7</span></a>). In this line of best fit, then, <span class="math inline">\(\hat\beta_0=2\)</span>.</p>
<p>The second parameter estimate in a simple regression is the <em>slope</em>, which is denoted as <span class="math inline">\(\hat\beta_1\)</span>. The slope is our official estimate of the relationship between <em>x</em> and <em>y</em>. Put another way, the slope represents the effect of <em>x</em> on <em>y</em>. The slope is also a rate of change: For a given change in x, how much does y change? When analysts talk about “cause-and-effect,” the “cause” is <em>x</em>, or a given change in <em>x</em>, and the “effect” is how much <em>y</em> increases or decreases as a result of the change in <em>x</em>. Note that this logic matches the descriptions of <em>x</em> as the independent variable and <em>y</em> as the dependent variable; in regression analysis, the predicted value of <em>y</em> depends on <em>x</em>. Importantly, the slope, which is the effect of <em>x</em> on <em>y</em>, is always in the units of measurement that <em>y</em> takes on.</p>
<p>Using either the “effect” or “rate of change” intuition, the slope equals “rise over run.” The “run” is a given change in <em>x</em>, while the rise is the associated change in <em>y</em> for that given change in <em>x</em>. When ascertaining what the slope estimate, <span class="math inline">\(\hat\beta_1\)</span>, equals, it is customary to work with a 1-unit increase in <em>x</em>, or a “run” of 1. As the graph highlights, when “run” equals 1, that means 1 will be in the denominator and whatever the rise is, that is what the slope, <span class="math inline">\(\hat\beta_1\)</span>, will equal. The graph above illustrates the slope on three separate parts of the graph. We could start at the y-intercept. For a 1-unit increase in <em>x</em> (run=1), we need a rise (or increase) of 1.5 to get back on the regression line. Thus, the slope estimate, <span class="math inline">\(\hat\beta_1\)</span>, is 1.5. That is, <strong>for a 1-unit increase in <em>x</em>, <em>y</em> increases by 1.5 units</strong>. We could also start at <em>x</em>=-2; in increase from -2 to -1 (the same run of 1), <em>y</em> increases from -5 to -3.5 (a rise of 1.5). And the same goes for starting at <em>x</em>=2. The point of showing this three times is to illustrate that in a standard linear regression, <em>the slope estimate is exactly the same across the entire regression line</em>.</p>
<p>Given the elegance of linear regression and the rise of over run logic, analysts can interpret the slope in a flexible manner. For example, a 2-unit increase in <em>x</em> generates a 3 unit increase in <em>y</em>. Simply multiply <em>both</em> the denominator and the numerator in the rise-over-run equation by 2. Visualize this on your own in the graph above. Moreover, a slope is 1.5 would also equal a “negative rise” (or decrease, -1.5) over a “negative run” (-1), i.e., <span class="math inline">\(\frac{-1.5}{-1}\)</span>. That is, a 1-unit <em>decrease</em> in <em>x</em> generates a 1.5-unit <em>decrease</em> in <em>y</em>.</p>
<p>Note that all the points we have discussed fall along the line of best fit, which means they are <em>predicted values</em> of <em>y</em>, or <span class="math inline">\(\hat{y}_i\)</span>, for given values of <em>x</em>. Thus, we could describe the line of best fit in the graph below as:</p>
<p><span class="math display">\[\hat{y}_i=\hat\beta_0+\hat\beta_1x_i\]</span> Once again, the equation contains two parameter estimates, <span class="math inline">\(\hat\beta_0\)</span> (y-intercept) and <span class="math inline">\(\hat\beta_1\)</span> (slope). This equation literally reflects the line of best in the graph above. However, returning to the graph below, we want to describe the line of best fit in the context of our sample data, which incorporates “errors,” or residuals.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="linreg1_files/figure-html/lbf7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<p>The <strong>sample regression equation for simple regression</strong> is thus:</p>
<p><span class="math display">\[y_i=\hat\beta_0+\hat\beta_1x_i +\hat{u}_i\]</span> Note that since <span class="math inline">\(\hat{u}_1\)</span> is added to the equation, we put <span class="math inline">\(y_i\)</span> instead of <span class="math inline">\(\hat{y}_1\)</span> on the left-hand side of the equation. This regression equation describes the sample. The “hats” above each <span class="math inline">\(\beta\)</span> mean that these are sample statistics, which are estimates of a parameter. When we do hypothesis testing later in the chapter, the sample statistic of interest will be <span class="math inline">\(\hat\beta_1\)</span>, which represents the effect of <em>x</em> on <em>y</em>. As discussed earlier, the OLS solution for actually estimating <span class="math inline">\(\hat\beta_0\)</span> and <span class="math inline">\(\hat\beta_1\)</span> has been around for many years. In simple regression, the solution for <span class="math inline">\(\hat\beta_1\)</span> is:</p>
<p><span class="math display">\[\hat\beta_1=\frac{\sum(x_i-\bar{x})(y_i-\bar{y})}{\sum(x_i-\bar{x})^2}=\frac{Cov(x, y)}{Var(x)}=r_{y,x}\frac{\hat\sigma_y}{\hat\sigma_x}\]</span> Note how <span class="math inline">\(\hat\beta_1\)</span> is first a function of covariance between <em>x</em> and <em>y</em>, or how <em>x</em> and <em>y</em> “go together” or are associated with one another. Since that component is in the numerator, the larger this covariance, the larger the slope estimate, <span class="math inline">\(\hat\beta_1\)</span>, will be. <span class="math inline">\(\hat\beta_1\)</span> in a simple regression is also a function of the variance of <em>x</em>, or how dispersed <em>x</em> is around the mean. Since this quantity is in the denominator, the larger this variance relative to <em>Cov(x, y)</em>, the smaller <span class="math inline">\(\hat\beta_1\)</span> will be. However, keep in mind that <em>Var(x)</em> will be related to <em>Cov(x, y)</em>. Note also that when Var(x) = 0, <span class="math inline">\(\hat\beta_1\)</span> is undefined (since division by 0 is impossible). That makes sense — if no variation exists in <em>x</em>, then <em>x</em> is by definition not a “variable” (i.e., “not able to vary”). Finally, in the last part of the equation above, <span class="math inline">\(\hat\beta_1\)</span> can be written in terms of Pearson’s correlation (<em>r</em>) between <em>x</em> and <em>y</em> as well as the sample standard errors for <em>x</em> and <em>y</em>. The equation shows how increases in correlation (in either the positive or negative direction, or as the value diverges away from 0) increase the size of <span class="math inline">\(\hat\beta_1\)</span>.</p>
<p>The equation for the y-intercept, <span class="math inline">\(\hat\beta_0\)</span>, in simple regression is: <span class="math inline">\(\hat\beta_0=\bar{y}-\hat\beta_1\bar{x}\)</span>. As I will discuss further below, the y-intercept, particularly in multiple regression, is not a meaningful quantity of interest. Analysts do report it, however, in regression output results. Instead, the focus of interpretation is the slope estimates, which represent the core quantities of interest.</p>
<p>The <strong>sample regression equation for multiple regression</strong> is below:</p>
<p><span class="math display">\[y_i=\hat\beta_0+\hat\beta_1x_{1i}+\hat\beta_2x_{2i}+\hat\beta_3x_{3i}...+\hat\beta_kx_{ki}+\hat{u}_i\]</span> In this equation, we add multiple <em>x</em> variables (more than 1), up to a total of <em>k</em> independent variables. How large can <em>k</em> get? Sometimes analysts will include 4 or 5 independent variables, and sometimes they might include 10 or so. Those are fairly conventional numbers for how many independent variables analysts include in a multiple regression equation. The critical benefit of multiple regression is that we are <strong>capturing the effect of, e.g.,</strong> <span class="math inline">\(x_1\)</span>, while <em>controlling for</em>, or <em>holding constant</em>, all other independent variables. Readers may know the Latin phrase for this logic as <em>ceteris paribus</em>, or “other things being equal.”</p>
<p>Recall the slope interpretation discussed earlier: For a 1-unit increase in <em>x</em>, <em>y</em> increases by <span class="math inline">\(\hat\beta_1\)</span> units. This effect of <em>x</em> on <em>y</em> in regression analysis is called a <strong>marginal effect</strong>. A marginal effect is a slope estimate at any given point on the regression surface. From the prior figure that described the regression line, recall that when we have a linear “functional form” between x and y (i.e., a straight line as opposed to, e.g., a parabola), the marginal effect is the same across the entire line.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>In multiple regression, the marginal effect of a given <em>x</em> variable on <em>y</em> is also called a <strong>partial effect</strong> because of the “controlling for” and “holding constant” interpretation above. This partial effect interpretation for a marginal effect in multiple regression is actually another example of differential calculus and specifically a partial derivative, i.e., the derivative of a function with respect to a specific variable, like <span class="math inline">\(x_1\)</span>: <span class="math inline">\(\frac{\partial{y}}{\partial{x_1}}\)</span>. In multiple regression, one can calculate such a partial derivative for each independent variable. Let’s say we have a multiple regression with 3 independent variables:</p>
<p><span class="math display">\[y_i=\hat\beta_0+\hat\beta_1x_{1i}+\hat\beta_2x_{2i}+\hat\beta_3x_{3i}+\hat{u}_i\]</span> When I take the partial derivative of the right-hand side of the equation with respect to <span class="math inline">\(x_1\)</span>, variables <em>other than</em> <span class="math inline">\(x_1\)</span> are treated as constants. The derivative of a constant is 0. And the derivative of <span class="math inline">\(\hat\beta_1x_{1i}\)</span> with respect to <span class="math inline">\(x_1\)</span> is simply <span class="math inline">\(\hat\beta_1\)</span>.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. That logic again underscores the elegance of the linear regression model and specifically the “linearity in the parameters” element where the equation follows a simple “parameter times variable + parameter times variable + parameter times variable” pattern. The marginal effect of a given <em>x</em> in a multiple regression equation is literally its effect on <em>y</em> while holding constant the other independent variables. Thus, the marginal, “partial” effect of each <em>x</em> variable can be written as:</p>
<p><span class="math display">\[\frac{\partial{y}}{\partial{x_1}}=\hat\beta_1\]</span> <span class="math display">\[\frac{\partial{y}}{\partial{x_2}}=\hat\beta_2\]</span> <span class="math display">\[\frac{\partial{y}}{\partial{x_3}}=\hat\beta_3\]</span></p>
<p>Multiple regression, and the estimation of “partial” effects, adds a causal layer to evaluating the relationship between <em>x</em> and <em>y</em>. Recall from <a href="intro.html" class="quarto-xref"><span>Chapter 2</span></a> that in experiments, random assignment of individuals to a treatment group (<em>x</em>=1) or control group (<em>x</em>=0) means that we are <em>controlling for</em>, or <em>holding constant</em>, every other individual-level variable. The treatment and control groups are equal, on average, in other traits. Multiple regression uses <em>statistics</em> instead of random assignment to control for additional independent variables; the researcher <em>manually</em> controls for additional factors that are necessary to account for. While multiple regression can never reach the peak level of causal inference that experiments reach, it is a step in the right direction. Discussion of regression assumptions below will continue with this topic.</p>
</section>
<section id="error-variance-goodness-of-fit-r2-and-standard-errors" class="level3" data-number="8.1.3">
<h3 data-number="8.1.3" class="anchored" data-anchor-id="error-variance-goodness-of-fit-r2-and-standard-errors"><span class="header-section-number">8.1.3</span> Error Variance, Goodness of Fit (<span class="math inline">\(R^2\)</span>), and Standard Errors</h3>
<p>The <strong>population regression equation for simple regression</strong> is:</p>
<p><span class="math display">\[y_i=\beta_0+\beta_1x_i +u_i\]</span> In simple regression, the true population parameters, for which we retrieve sample estimates, are <span class="math inline">\(\beta_0\)</span>, the population y-intercept, and <span class="math inline">\(\beta_1\)</span>, the population slope. Like any parameter from the equation above, each parameter is an unknown quantity from the population about which we want to make an inference based on our sample. One part of interpreting regression output is to engage with <em>inferential statistics</em> to draw inferences about the sample statistics relative to the population. That means we need to estimate a <strong>standard error</strong> for our slope estimate, <span class="math inline">\(\hat\beta_1\)</span>. One critical piece of information we need first is the <strong>error variance</strong>, or residual variance, from the regression equation. This is denoted as <span class="math inline">\(\hat\sigma_\hat{u}^2\)</span>. It represents how much dispersion exists in the residuals, which recall are the “misses” from the observed value of <em>y</em> (<span class="math inline">\(y_i\)</span>) to the predicted value of <em>y</em> (<span class="math inline">\(\hat{y}_i\)</span>).</p>
<p>We have already discussed the “sum of squared residuals,” or SSR, which is the sum over all observations of the squared deviations between <span class="math inline">\(y_i\)</span> and <span class="math inline">\(\hat{y}_i\)</span>. To get the error variance, we divide that quantity by the <em>degrees of freedom</em>, which in regression is <em>N - k - 1</em>; <em>k</em> is equal to the total number of independent variables in the regression model. In simple regression with just one independent variable, <em>k</em>=1. If there are 7 independent variables, <em>k</em>=7. The extra “1” in the degrees of freedom equation is for the y-intercept, <span class="math inline">\(\hat\beta_0\)</span>. Recall that degrees of freedom generally is sample size minus the total number of parameters we have to estimate. Thus, the error variance can be written as:</p>
<p><span class="math display">\[\hat\sigma_\hat{u}^2=\frac{SSR}{N-k-1}\]</span> While it is most common to work with error variance, the square root of this quantity, <span class="math inline">\(\hat\sigma_\hat{u}\)</span>, is called the <em>standard error of the regression</em>.</p>
<p>Importantly, error variance represents what is left <em>unexplained</em> in a regression equation. Our independent variables explain variation in <em>y</em>, from a “goodness of fit” perspective, while the error variance captures how much “random noise” there is in <em>y</em>, i.e., how much variance in <em>y</em> that is left unexplained.</p>
<p>The flipside of error variance is a <strong>goodness-of-fit statistic,</strong> <span class="math inline">\(R^2\)</span>, which captures the fraction of the variance in <em>y</em> that our included independent variables explain. <span class="math inline">\(R^2\)</span> is derived from understanding two more “sum of squares” quantities, in addition to the aforementioned SSR. These include the “total sum of squares” (SST) and “explained sum of squares” (SSE).</p>
<p><span class="math display">\[SST=\sum\limits_{i=1}^N(y_i-\bar{y})^2\]</span> <span class="math display">\[SSE=\sum\limits_{i=1}^N(\hat{y}_i-\bar{y})^2\]</span></p>
<p>SST represents the <em>total variation in y</em>, while SSE represents the <em>explained variation in y</em>, i.e., the variation in <em>y</em> explained by the independent variables. Since SSR represents the <em>unexplained variation</em> in <em>y</em>, one can see how these three sums of squares are related:</p>
<p><span class="math display">\[SST = SSR + SSE\]</span> <span class="math display">\[SSR=SST-SSE\]</span> <span class="math display">\[SSE=SST-SSR\]</span></p>
<p>As a goodness-of-fit measure, <span class="math inline">\(R^2\)</span> represents how much variance, or variation, in <em>y</em> is explained by the independent variables in the regression. Thus, the equation for <span class="math inline">\(R^2\)</span> is:</p>
<p><span class="math display">\[R^2=1-\frac{SSR}{SST}=\frac{SSE}{SST}\]</span></p>
<p><span class="math inline">\(R^2\)</span> is a proportion that ranges from 0 to 1. Researchers will commonly multiply the value by 100 to turn it into a percentage. They will often interpret <span class="math inline">\(R^2\)</span> as follows: The independent variables explain about <em>Z</em>% of the variance in <em>y</em> (where <em>Z</em> is a number between 0 and 100). In simple regression, <span class="math inline">\(R^2\)</span> is literally Pearson’s correlation, <em>r</em>, squared. Thus, correlation relates to regression, particularly in how we discussed that for very high correlations, the datapoints will be tightly packed around the line of best fit. The same logic goes for <span class="math inline">\(R^2\)</span>: The tighter the datapoints are dispersed around the line of best fit, the higher <span class="math inline">\(R^2\)</span> will be. In practice, it is common for researchers to report <span class="math inline">\(R^2\)</span> values in the range of 0.10 to 0.30. Those are actually quite normal in survey research. For country-level analysis, like in V-Dem, <span class="math inline">\(R^2\)</span> may be higher — in the ballpark of 0.50 or 0.60. <span class="math inline">\(R^2\)</span> values that fall below 0.05 are in the smaller range. While reporting and interpreting <span class="math inline">\(R^2\)</span> is important, in regression analysis, researchers prioritize interpretation and inference of the slope (<span class="math inline">\(\hat\beta\)</span>) estimates.</p>
<p>In simple regression, the <strong>sampling variance</strong> of the slope estimate, <span class="math inline">\(\hat\beta_1\)</span>, is:</p>
<p><span class="math display">\[Var(\hat\beta_1)=\frac{\hat\sigma_\hat{u}^2}{\sum(x_i-\bar{x})^2}\]</span></p>
<p>Then, the <strong>standard error of the slope estimate,</strong> <span class="math inline">\(\hat\beta_1\)</span>, in simple regression is simply the square root of this equation:</p>
<p><span class="math display">\[SE(\hat\beta_1)=\sqrt{Var(\hat\beta_1)}\]</span></p>
<p>Analysts use this standard error estimate in conjunction with <span class="math inline">\(\hat\beta_1\)</span> to do inferential statistics exactly the same way we did so in <a href="inferential.html" class="quarto-xref"><span>Chapter 7</span></a>, particularly in the difference of means test.</p>
<p>Note that in simple regression, three factors influence the size of the standard errors: (1) sample size, <em>N</em> (which enters in through the error variance equation); (2) error variance, <span class="math inline">\(\hat\sigma^2_\hat{u}\)</span>; and (3) variance in <em>x</em>. Each factor relates to how we discussed sampling error in <a href="inferential.html" class="quarto-xref"><span>Chapter 7</span></a>. The more <em>informative</em> the data are, the lower the random sampling error, or standard error estimate. The larger the sample size, the more informative our data, and the smaller our standard error. The smaller the error variance, the more our independent variables are explaining <em>y</em>. Recall the prior graph showing variation in “goodness of fit.” The lower the goodness of fit, the higher the error variance — the datapoints are widely dispersed around the line of best fit. The higher the goodness of fit, the lower the error variance. Thus, lower error variance is associated with a smaller standard error of <span class="math inline">\(\hat\beta_1\)</span>. Finally, the more variance there is in <em>x</em> (and thus the more information there is in <em>x</em>), the lower the standard error.</p>
<p>In multiple regression, one more aspect is added to the sampling variance for a given <em>x</em> variable. The following is the equation for the sampling variance for a <span class="math inline">\(\hat\beta_j\)</span> associated given independent variable, <span class="math inline">\(x_j\)</span>:</p>
<p><span class="math display">\[Var(\hat\beta_j)=\frac{\hat\sigma_\hat{u}^2}{\sum(x_i-\bar{x})^2(1-R_j^2)}\]</span></p>
<p>And once again, to get the standard error for <span class="math inline">\(\hat\beta_j\)</span>:</p>
<p><span class="math display">\[SE(\hat\beta_j)=\sqrt{Var(\hat\beta_j)}\]</span></p>
<p>In the sampling variance equation, note that the additional item relative to the simple regression equation is <span class="math inline">\((1-R_j^2)\)</span> in the denominator. <span class="math inline">\(R_j^2\)</span> is <em>NOT</em> the model <span class="math inline">\(R^2\)</span> as discussed above. Instead, <span class="math inline">\(R_j^2\)</span> is a measure of multicollinearity among the <em>x</em> variables in the model. <strong>Multicollinearity</strong> means how correlated the <em>x</em> variables are with each other. It is literally the <span class="math inline">\(R^2\)</span> from this regression model (in the case of three independent variables):</p>
<p><span class="math display">\[x_{1i}=\hat\beta_0+\hat\beta_1x_{2i}+\hat\beta_2x_{3i}+\hat{u}_i\]</span></p>
<p>That equation may seem counterintuitive. For a given <span class="math inline">\(x_j\)</span>, <span class="math inline">\(R_j^2\)</span> measures how much variation in <span class="math inline">\(x_j\)</span> is explained by remaining <em>x</em> variables. As this multicollinearity increases, the standard error will increase as well. Once again, think of factors that influence standard errors as “informational issues.” If the other <em>x</em> variables are strongly correlated with <span class="math inline">\(x_j\)</span>, that means <span class="math inline">\(x_j\)</span> is not bringing a great of <em>unique</em> information to the regression context; it is not really “holding its own.” It is not as informative because it overlaps so much with variation from the other <em>x</em> variables. Thus, in multiple regression, we can now summarize the four factors that influence the size of standard errors:</p>
<p><strong>Four Factors that Influence the Size of Standard Errors in Multiple Regression:</strong></p>
<ol type="1">
<li>As <strong>sample size, <em>N</em>,</strong> increases, standard errors will decrease.</li>
<li>As <strong>error variance</strong>, <span class="math inline">\(\hat\sigma^2_\hat{u}\)</span>, increases, standard errors will also increase.</li>
<li>As <strong>variation in a given <em>x</em></strong> increases, the standard error for that given <span class="math inline">\(\hat\beta\)</span> will decrease.</li>
<li>As <strong>multicollinearity for a given <em>x</em></strong> increases, the standard error for that given <span class="math inline">\(\hat\beta\)</span> will increase.</li>
</ol>
</section>
</section>
<section id="regression-assumptions" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="regression-assumptions"><span class="header-section-number">8.2</span> Regression Assumptions</h2>
<p>The OLS regression method contains multiple assumptions that are required for certain types of interpretations about both the slope estimates and the standard errors.</p>
<section id="linearity-in-the-parameters" class="level3" data-number="8.2.1">
<h3 data-number="8.2.1" class="anchored" data-anchor-id="linearity-in-the-parameters"><span class="header-section-number">8.2.1</span> Linearity in the Parameters</h3>
<p>This first assumption centers on a more functional concern about our model specification. “Linearity in the parameters” means that the regression follows this basic form of “parameter times variable” plus “parameter times variable” plus “parameter times variable.” The parameters, the <span class="math inline">\(\beta\)</span>s, are multipliers. These <span class="math inline">\(\beta\)</span>s cannot be transformed from the form in the equation below.</p>
<p><span class="math display">\[y_i=\beta_0+\beta_1x_{1i}+\beta_2x_{2i}+\beta_3x_{3i}+{u}_i\]</span></p>
<p>In other words, they cannot be squared or exponentiated. This equation would be <strong>nonlinear in the parameters</strong>:</p>
<p><span class="math display">\[y_i=\beta_0+\beta_1^2x_{1i}+exp(\beta_2)x_{2i}+x_{3i}^{\beta_3}+{u}_i\]</span></p>
<p>Any transformation to a <span class="math inline">\(\beta\)</span> itself in the equation makes the equation <em>nonlinear</em> in the parameters.</p>
<p>Importantly, this assumption is about the <span class="math inline">\(\beta\)</span>s and <em>not</em> the <em>x</em> variables. This marks the difference between linearity in the parameters versus <strong>linear and nonlinear functional forms between <em>x</em> and <em>y</em></strong>. Recall the discussion from <a href="dataviz.html" class="quarto-xref"><span>Chapter 4</span></a> about nonlinear functional forms. While we have thus far centered most material around linear functional forms, where the line of best fit is a straight line (i.e., linear), OLS can accommodate nonlinear relationships, or nonlinear functional forms, between x and y. In most political science contexts, researchers estimate linear functional forms. But some theories specifically call for a nonlinear functional form between <em>x</em> and <em>y</em>. To formalize this difference, consider the equations below.</p>
<p><strong>Linearity in the parameters, nonlinear functional form between <span class="math inline">\(x_1\)</span> and <span class="math inline">\(y\)</span></strong>:</p>
<p><span class="math display">\[y_i=\beta_0+\beta_1x_{1i}^2+\beta_2x_{2i}+\beta_3x_{3i}+{u}_i\]</span></p>
<p>In this case, we transform <span class="math inline">\(x_1\)</span> by squaring it. This is an example of an “exponential” functional form, where the effect <em>x</em> is smaller at lower ranges of <em>x</em> but then “takes off” and becomes very large at higher ranges of <em>x</em>. Note that the linearity in the parameters assumption is upheld in this equation because <span class="math inline">\(\beta_1\)</span> is an untransformed multiplier.</p>
</section>
<section id="observations-are-independent-from-one-another" class="level3" data-number="8.2.2">
<h3 data-number="8.2.2" class="anchored" data-anchor-id="observations-are-independent-from-one-another"><span class="header-section-number">8.2.2</span> Observations are Independent from One Another</h3>
<p>OLS also assumes that the observations, or units of analysis, are independent from one another. That is, observation 1’s values of <em>y</em> and <em>x</em> do not depend on observation 2 or 3’s values. When observations are chosen via <strong>random sampling</strong>, this assumption holds. An example where this assumption would not hold is if I did house-to-house surveys, and I surveyed multiple adults in the same household (e.g., spouses or in a multigenerational home, the parents and the grandparents). In this case, the values of variables for people in the same household may be related because of shared experiences. Those observations would not be independent of one another.</p>
<p>Thus, random sampling is the gold standard for meeting this assumption. This assumption can break down in other settings, like time series data (see <a href="intro.html" class="quarto-xref"><span>Chapter 2</span></a>) where the observations fall in sequential time points like years or months. If we are tracking unemployment across time, past values are not independent of current values. Thus, when analysts examine such time series data, they account for this temporal dependence.</p>
</section>
<section id="exogeneity" class="level3" data-number="8.2.3">
<h3 data-number="8.2.3" class="anchored" data-anchor-id="exogeneity"><span class="header-section-number">8.2.3</span> Exogeneity</h3>
<p>The exogeneity assumption is the most important assumption for purposes of maximizing the causal and <em>ceteris paribus</em> interpretations of the <span class="math inline">\(\beta\)</span> estimates. Exogeneity is an assumption about our independent variables. “Independent” means that an <em>x</em> variable is independent from both <em>y</em> and the other <em>x</em> variables. It may seem strange to think of <em>x</em> as being “independent” from <em>y</em>, but what I mean is that <em>x</em> is not simultaneously caused by or influenced by <em>y</em>. In other words, <em>y</em> depends on x, but <em>x</em> does not depend on <em>y</em>. <em>x</em> is the “influencer” in the relationship; it is “causally prior” to <em>y</em>. When exogeneity fails and <em>x</em> actually does depend on <em>y</em>, <em>x</em> is said to be <strong>endogenous</strong>. Put another way, including this type of <em>x</em> variable in our regression model induces <em>endogeneity</em>, which is the opposite of exogeneity and thus a violation of this assumption.</p>
<p>An <em>x</em> variable can also be endogenous to other independent variables in the model. Let’s say we have reason to believe that <span class="math inline">\(x_2\)</span> may cause <span class="math inline">\(x_1\)</span>, which would mean that <span class="math inline">\(x_1\)</span> is potentially an endogenous explanatory variable in the model. This endogeneity poses a specific threat to the <em>ceteris paribus</em> condition behind partial marginal effects. Recall that a partial effect is the effect of <em>x</em> (e.g, for a one-unit increase in <em>x</em>) on <em>y</em> while controlling for or <em>holding constant the remaining x variables</em>. If <span class="math inline">\(x_1\)</span> depends on <span class="math inline">\(x_2\)</span>, then we cannot vary <span class="math inline">\(x_1\)</span> (a one-unit increase) without <span class="math inline">\(x_2\)</span> also varying; in other words, we cannot vary <span class="math inline">\(x_1\)</span> while holding <span class="math inline">\(x_2\)</span> constant. And the same goes for the marginal effect of <span class="math inline">\(x_2\)</span>. In these cases, one <em>x</em> variable <em>confound</em> the effect of another <em>x</em> variable.</p>
<p>In sum, an <em>x</em> variable is exogenous if it is not explained by any other variable in the regression model. <em>x</em> is endogenous if it is explained by another variable in the regression model, which poses a major threat to the causal direction from <em>x</em> to <em>y</em>.</p>
<p>Exogeneity is a key assumption for causal inference, but it is not the only one, of course. The assumption is connected to the classic “correlation versus causation” conundrum. Under the exogeneity assumption, the causal flow goes one way: From <em>x</em> to <em>y</em>. For correlation per se, researchers are agnostic about the causal flow and are only concerned with how much two variables “go together.” Think about the covariance equation or the correlation equation from <a href="descriptive.html" class="quarto-xref"><span>Chapter 6</span></a>. That equation has nothing to do with the causal flow from one variable to another. The linear regression model, by the very nature of how we specify <em>y</em> as a function of <em>x</em>, <em>does</em> specify this causal flow, so we have to posit a specific assumption about exogeneity. As <a href="intro.html" class="quarto-xref"><span>Chapter 2</span></a> discussed, researchers use <em>theory and hypotheses</em> to specify a causal relation between <em>x</em> and <em>y</em>.</p>
<p>Second, researchers use research design as a setup for the empirical estimation of causal effects of <em>x</em> on <em>y</em>. As discussed earlier, regression analysis requires researchers to manually specify the additional <em>x</em> variables they should control for; statistics, and the estimation of “partial effects,” do the heavy lifting on <em>ceteris paribus</em> grounds. That is a major difference from experiments — the gold standard for causal inference — which do the heavy lifting for causal inference on the <em>design side</em> via random assignment to treatment versus control groups.</p>
</section>
<section id="residuals-are-white-noise" class="level3" data-number="8.2.4">
<h3 data-number="8.2.4" class="anchored" data-anchor-id="residuals-are-white-noise"><span class="header-section-number">8.2.4</span> Residuals are “White Noise”</h3>
<p>Once we estimate our model, including all necessary independent variables, we assume that the residuals, which capture “unexplained” or omitted explanatory factors, are “white noise,” or completely random. This assumption speaks to the population but has implications for the sample aspects. First, the residuals, <span class="math inline">\(u_i\)</span>, follow a <em>normal probability distribution</em> with mean 0 and a variance that equals the aforementioned “error variance” at the population level, <span class="math inline">\(\sigma_u^2\)</span>. This is written as:</p>
<p><span class="math display">\[u_i \sim N(0, \sigma_u^2)\]</span></p>
<p>The equation means that the residuals are drawn from a population with a mean of 0; they are centered on the regression line such that the average residual is 0. In population form, we say that the <em>expected value</em> is 0. Since <em>y</em> is a function of the residual, <em>u</em>, <em>y</em> is also assumed to be normally distributed, written in population form:</p>
<p><span class="math display">\[y_i \sim N(\beta_0+\beta_1x_{1i}+\beta_2x_{2i}...+\beta_kx_{ki},~ \sigma_u^2)\]</span></p>
<p>That is, each <em>y</em> value is drawn from a normal distribution with a mean that is the “true” regression line and the same error variance, <span class="math inline">\(\sigma_u^2\)</span>.</p>
<p>The second part of the “white noise” element of the residuals is based on the error variance, <span class="math inline">\(\sigma_u^2\)</span>. Note that each residual, <span class="math inline">\(u_i\)</span>, is drawn from a distribution with the <em>same</em> error variance, <span class="math inline">\(\sigma_u^2\)</span>. This leads to the second aspect of this assumption that the residuals are assumed to be “homoscedastic.” <strong>Homoscedasticity</strong> means that the error variance is assumed to be <em>constant</em> across the entire regression surface; the error variance is <span class="math inline">\(\sigma_u^2\)</span> at low, middle, and high values of the <em>x</em> distribution. The graph below illustrates both the normality and homoscedasticity assumptions for three data points.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="linreg1_files/figure-html/whitenoise-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>Once again, this represents the population regression, where datapoints are drawn from a normal distribution that is centered on the regression line (via the assumptions above). The opposite of homoscedasticity is <strong>heteroscedasticity</strong>, which means that the error variance, <span class="math inline">\(\sigma_u^2\)</span>, would be <em>different</em> across the range of <em>x</em>. The homoscedasticity assumption is most critical for the standard error estimates. Because <span class="math inline">\(\sigma_u^2\)</span> is in the numerator of the standard error formula, the presence of heteroscedasticity would imply that the standard errors would also be different across the range of <em>x</em>, which OLS cannot accommodate. Methods exist — e.g., the use of “robust standard errors” — to account for the existence of heteroscedasticity by making corrections to the standard errors.</p>
<p>An implication from the second assumption above (observations are independent) is that the residuals are also uncorrelated with each other, which is another way to say that the residuals are independent from one another.</p>
</section>
<section id="no-perfect-multicollinearity" class="level3" data-number="8.2.5">
<h3 data-number="8.2.5" class="anchored" data-anchor-id="no-perfect-multicollinearity"><span class="header-section-number">8.2.5</span> No Perfect Multicollinearity</h3>
<p>Recall that the estimate of multicollinearity for each independent variable, <span class="math inline">\(R^2_j\)</span>, is included in the formula for standard errors in multiple regression. While OLS can handle <em>some</em> degree of multicollinearity, it cannot handle a <em>perfect</em> degree of multicollinearity, i.e., when <span class="math inline">\(R^2_j=1\)</span>. One can see that when <span class="math inline">\(R^2_j=1\)</span>, the standard error estimate is undefined (division by zero). It can be shown in the derivation of the partial slopes, <span class="math inline">\(\hat\beta\)</span>, in multiple regression that <span class="math inline">\(R^2_j=1\)</span> also triggers an undefined <span class="math inline">\(\hat\beta\)</span>. The assumption also makes sense intuitively. If three or four other independent variables perfectly account for <em>x</em>, then <em>x</em> and those other variables are attempting to exert similar types of influence in the regression model. <em>x</em> is incapable of exerting any unique influence.</p>
<p>This issue is more of a “functional assumption.” Researchers would almost surely not include independent variables in a regression model that would trigger perfect multicollinearity. On the other hand, researchers do need to be attuned to high levels of multicollinearity and their effects on standard errors as well as slope estimates.</p>
</section>
</section>
<section id="simple-regression-estimation-and-interpretation" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="simple-regression-estimation-and-interpretation"><span class="header-section-number">8.3</span> Simple Regression: Estimation and Interpretation</h2>
<p>I now move to applications of regression analysis using datasets from prior chapters. I begin with simple regression (just one independent variable), and I return to the example from <a href="inferential.html" class="quarto-xref"><span>Chapter 7</span></a> on the effect of social media consumption on affective polarization. <a href="inferential.html" class="quarto-xref"><span>Chapter 7</span></a> concluded with a difference of means hypothesis test of whether those high in social media consumption have higher affective polarization than those low in social media consumption. The results showed that social media consumption does indeed increase affective polarization, and the effect was statistically significant.</p>
<p>Below, I report the same test using linear regression instead. As I will show, we get the exact same result because a simple regression is doing the exact same thing as a difference of means test in this example: It is generating the difference in affective polarization between the low and high affective polarization groups, and it is evaluating whether that difference is statistically significant. Linear regression is extremely valuable for hypothesis testing because one can conduct such testing in one fell swoop by examining the regression output.</p>
<p>Key to interpreting regression output is using the aforementioned “3 S’s” framework for interpreting slope estimates, <span class="math inline">\(\hat\beta\)</span>. Researchers commonly call the slope estimates <strong>regression coefficients</strong> as well. Recall that the slope estimates (and partial slope estimates in multiple regression) take center stage in regression analysis. We are evaluating the effect of <em>x</em> on <em>y</em>, and <span class="math inline">\(\hat\beta\)</span> gives us critical information on this effect.</p>
<p><strong>3 S’s Framework for Interpreting the Effects of <em>x</em> on <em>y</em> (</strong><span class="math inline">\(\hat\beta\)</span>)</p>
<ol type="1">
<li><p><strong>Sign</strong>, or the <em>direction</em> of the effect (positive or negative). When interpreting the direction of the effect of <em>x</em> on <em>y</em>, make it substantive, like you are answering the hypothesis. For example, “As <em>x</em> increases, <em>y</em> increases as well.”</p></li>
<li><p><strong>Size</strong>: As discussed in this chapter, linear regression gives us an elegant, powerful means of communicating size via the rise-over-run interpretation of a slope estimate, <span class="math inline">\(\hat\beta\)</span>. If <span class="math inline">\(\hat\beta\)</span> has a positive sign, that means that <em>for a one-unit increase in x, y increases by</em> <span class="math inline">\(\hat\beta\)</span> units. If <span class="math inline">\(\hat\beta\)</span> is negative, for a <em>for a one-unit increase in x, y decreases by</em> <span class="math inline">\(\hat\beta\)</span> units. Remember to always communicate these “unit increases or decreases” in terms of the measurement units the <em>x</em> and <em>y</em> variables take on. Analysts can communicate additional interpretations based on the ease of interpreting a slope estimate. For example, “for a 10-unit increase in <em>x</em>, <em>y</em> increases by <span class="math inline">\(\hat\beta \times10\)</span> units.”</p></li>
<li><p><strong>Statistical significance</strong>: Linear regression makes doing inferential statistics very simple because all of the key information we need — the <span class="math inline">\(\hat\beta\)</span>s, standard errors, test statistics (<em>t</em>), and the p-values — is included in the output. Moreover, we assume that the null hypothesis, <span class="math inline">\(H_0\)</span>, is 0, i.e., that the effect of <em>x</em> of <em>y</em> is 0. That means that for a given <span class="math inline">\(\hat\beta\)</span>, we can look directly at the p-value associated with the test statistic (<em>t</em>), which follows Student’s t distribution (from <a href="inferential.html" class="quarto-xref"><span>Chapter 7</span></a>), and draw a conclusion about statistical significance. If <span class="math inline">\(p &lt; 0.05\)</span> (assuming the 95% confidence level, or <span class="math inline">\(\alpha\)</span>=0.05), the effect of <em>x</em> on <em>y</em> is statistically significant. If <span class="math inline">\(p \ge 0.05\)</span>, then the effect of <em>x</em> on <em>y</em> is not statistically significant (or statistically insignificant). Once again, in significance testing of this sort, we are making an inference from sample to population and evaluating whether the sample statistic, <span class="math inline">\(\hat\beta\)</span>, is significantly different from 0 (the null hypothesis value).</p></li>
</ol>
<p>The 3 S’s framework captures the nuts and bolts of interpreting regression output. It is the primary way that social scientists communicate their results in journal articles and books. In addition to interpreting the slope estimates, analysts also interpret the regression model’s <span class="math inline">\(R^2\)</span>, which captures the overall fit of the model to the data. In situations where researchers suspect that certain regression assumptions are not met, they will often conduct diagnostics or “robustness checks” to ensure that the results do not change because of an issue in the regression model.</p>
<section id="social-media-consumption-and-affective-polarization" class="level3" data-number="8.3.1">
<h3 data-number="8.3.1" class="anchored" data-anchor-id="social-media-consumption-and-affective-polarization"><span class="header-section-number">8.3.1</span> Social Media Consumption and Affective Polarization</h3>
<p>And now, I return to the example of the effect of social media consumption on affective polarization in the American public. The code below reviews how I coded both affective polarization and social media consumption.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(labelled)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>anes <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"https://blbartels.github.io/dataps/anes24.dta"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>anes <span class="ot">&lt;-</span> anes <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">partyid =</span> <span class="fu">if_else</span>(V241227x<span class="sc">&lt;</span><span class="dv">0</span>, <span class="cn">NA</span>, V241227x), </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>                       <span class="at">demtherm =</span> <span class="fu">if_else</span>(V241166<span class="sc">&lt;</span><span class="dv">0</span>, <span class="cn">NA</span>, V241166), </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>                       <span class="at">reptherm =</span> <span class="fu">if_else</span>(V241167<span class="sc">&lt;</span><span class="dv">0</span>, <span class="cn">NA</span>, V241167)) <span class="sc">|&gt;</span> </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">set_value_labels</span>(<span class="at">partyid=</span><span class="fu">c</span>(<span class="st">"Str Dem"</span><span class="ot">=</span><span class="dv">1</span>, <span class="st">"Wk Dem"</span><span class="ot">=</span><span class="dv">2</span>, <span class="st">"Ind Dem"</span><span class="ot">=</span><span class="dv">3</span>, </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>                             <span class="st">"Ind"</span><span class="ot">=</span><span class="dv">4</span>, <span class="st">"Ind Rep"</span><span class="ot">=</span><span class="dv">5</span>, <span class="st">"Wk Rep"</span><span class="ot">=</span><span class="dv">6</span>, </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>                             <span class="st">"Str Rep"</span><span class="ot">=</span><span class="dv">7</span>)) </span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>anes <span class="ot">&lt;-</span> anes <span class="sc">|&gt;</span> </span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">party3 =</span> <span class="fu">case_when</span>(</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>           partyid<span class="sc">&gt;</span><span class="dv">0</span> <span class="sc">&amp;</span> partyid<span class="sc">&lt;</span><span class="dv">4</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>           partyid <span class="sc">==</span> <span class="dv">4</span> <span class="sc">~</span> <span class="dv">2</span>,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>           partyid<span class="sc">&gt;</span><span class="dv">4</span> <span class="sc">~</span> <span class="dv">3</span>))</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Affective polarization</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>anes <span class="ot">&lt;-</span> anes <span class="sc">|&gt;</span> </span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">affpol =</span> <span class="fu">if_else</span>(party3<span class="sc">==</span><span class="dv">1</span>, demtherm<span class="sc">-</span>reptherm, <span class="cn">NA</span>), </span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>         <span class="at">affpol =</span> <span class="fu">if_else</span>(party3<span class="sc">==</span><span class="dv">3</span>, reptherm<span class="sc">-</span>demtherm, affpol), </span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>         <span class="at">affpol =</span> <span class="fu">if_else</span>(affpol<span class="sc">&lt;</span><span class="dv">0</span>, <span class="cn">NA</span>, affpol))</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Social media consumption</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>anes <span class="ot">&lt;-</span> anes <span class="sc">|&gt;</span> </span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">socialmed =</span> <span class="fu">if_else</span>(V242406<span class="sc">&gt;=</span><span class="dv">5</span>, <span class="dv">1</span>, <span class="cn">NA</span>),</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>         <span class="at">socialmed =</span> <span class="fu">if_else</span>(V242406<span class="sc">&gt;=</span><span class="dv">0</span> <span class="sc">&amp;</span> V242406<span class="sc">&lt;=</span><span class="dv">4</span>, <span class="dv">0</span>, socialmed))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Affective polarization ranges from 0 (no affective polarization) to 100 (extreme high affective polarization). Recall that it is the difference in one’s evaluation of their in-party versus their out-party. It reflects how much more they like their party compared to the other party. The units of measurement are “degrees” using the thermometer rating scale. Each one-unit change is a “one-degree” change. For social media consumption, 1=high consumption, 0=low consumption. Recall that in data analysis, including regression analysis, binary independent variables are also called “dummy variables.” They provide a group comparison.</p>
<p>To estimate the simple regression, analysts use the <code>lm</code> (“linear model”) command in RStudio. This is a base R command, so one does not need to load a package to use it. Unfortunately, the <code>lm</code> command is not compatible with piping, so users need to specify the dataset to be analyzed within the parentheses.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(affpol <span class="sc">~</span> socialmed, <span class="at">data=</span>anes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = affpol ~ socialmed, data = anes)

Coefficients:
(Intercept)    socialmed  
     53.715        4.274  </code></pre>
</div>
</div>
<p>When we run this command, the output is underwhelming to say the least. The only output we get is the y-intercept, or <span class="math inline">\(\hat\beta_0\)</span>=53.715, and the slope for the effect of social media, <span class="math inline">\(\hat\beta_1\)</span>=4.274. I will show better ways to report regression output below. Recall that <span class="math inline">\(\hat\beta_0\)</span> represents the predicted value of affective polarization, <span class="math inline">\(\hat{y}\)</span>, when <em>x</em>=0, which in this case is the low social media consumption group. Thus, the predicted value of affective polarization for this group is 53.715 degrees.</p>
<p>The slope estimate is the difference in affective polarization between the low and high social media groups. The number should look familiar from <a href="inferential.html" class="quarto-xref"><span>Chapter 7</span></a>. It is literally the difference between the mean of affective polarization for low versus high social media consumption groups. That number is 4.274. This matches up with the rise-over-run slope interpretation as well. For the social media dummy variable, a “1-unit increase” is simply an increase from the low social media consumption group (=0) to the high consumption group (=1). Thus, “for a 1-unit increase in social media consumption (from low to high), affective polarization increases by a 4.274 degrees.</p>
<p>RStudio contains several packages for converting regression output into table form that are suitable for presentation and publication. For RStudio users generating .pdf documents of an article or presentation, packages such as <code>texreg</code>, <code>stargazer</code>, and <code>huxtable</code> are popular. Below, I use the <code>texreg</code> package, which can be used for .pdf documents or .html documents (like what I am using here). In the code below, note that I save my regression object as “a.” That allows me to give the core information to the <code>texreg</code> package, which uses that information and packages it in a nice-looking, presentable table. Next, I use the <code>htmlreg</code> command to display the table. After <code>list</code>, I enter my saved regression model object, a. I can include a caption, or title, for the regression model. Using the defaults from <code>htmlreg</code>, I get the following table. Note that for analysts generating .pdf documents in Quarto, one would use the command <code>texreg</code> instead of <code>htmlreg</code>.</p>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(texreg)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a couple of sample models</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">lm</span>(affpol <span class="sc">~</span> socialmed, <span class="at">data=</span>anes)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Output as HTML</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">htmlreg</span>(<span class="fu">list</span>(a), </span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">caption =</span> <span class="st">"&lt;b&gt;The Effect of Social Media on Affective Polarization&lt;/b&gt;"</span>, </span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">center =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;">
<caption>
<b>The Effect of Social Media on Affective Polarization</b>
</caption>
<thead>
<tr>
<th style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 1
</th>
</tr>
</thead>
<tbody>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
(Intercept)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
53.71<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.55)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
socialmed
</td>
<td style="padding-left: 5px;padding-right: 5px;">
4.27<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.96)
</td>
</tr>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.00
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Adj. R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.00
</td>
</tr>
<tr style="border-bottom: 2px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
Num. obs.
</td>
<td style="padding-left: 5px;padding-right: 5px;">
4221
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="font-size: 0.8em;" colspan="2">
<sup>***</sup>p &lt; 0.001; <sup>**</sup>p &lt; 0.01; <sup>*</sup>p &lt; 0.05
</td>
</tr>
</tfoot>
</table>
<p>This table is highly effective, though several improvements can be made. First, notice that the table reports raw variable names (“socialmed”) and also “(Intercept)” for the y-intercept estimate, <span class="math inline">\(\hat\beta_0\)</span>. Researchers should always change the variable names from the “raw” names in the dataset to a more descriptive name that readers can understand. The goal of a regression table is to make it as stand-alone as possible. Thus, I need to change these names. The table reports <span class="math inline">\(\hat\beta_0\)</span> and <span class="math inline">\(\hat\beta_1\)</span>. In parentheses below, the table reports <em>standard errors</em> for each estimate. This is standard reporting procedure for regression output. Always report the regression coefficients and the standard errors.</p>
<p>The table uses a common means of reporting p-values and statistical significance, or what might be called the “star system.” Three asterisks indicates that a p-value for a given coefficient is less than 0.001 (p&lt;0.001), i.e., a very small p-value indicating a “highly” statistically significant effect. Two asterisks means p&lt;0.01, while one asterisk means p&lt;0.05. All three asterisk designations represent statistically significant effects. Users can change the “star system” in the options with the following command: <code>stars = c(0.01, 0.05, 0.10)</code>. If I entered this in the commands, it would report p&lt;0.01, p&lt;0.05, and p&lt;0.10. Some users will use p&lt;0.10 to denote effects that are sometimes referred to as “marginally significant effects,” i.e., effects not significant at the 95% confidence level but significant at the less stringent 90% confidence level.</p>
<p>As mentioned earlier in this chapter, regression analysis, and the reporting of results in a table like this one, allow researchers to conduct hypothesis tests in one fell swoop. With the asterisks designation, we can instantly see that the effect of social media consumption on affective polarization is statistically significant at the 95% confidence level (and actually at the 99.9% confidence level since p&lt;0.001). Researchers can execute the “3 S’s” interpretive framework just by looking at the result for the social media variable. It has a positive sign, we have already interpreted the size, and it is statistically significant. Researchers rarely, if ever, interpret the y-intercept because it rarely gives us much information at all, especially in multiple regression where its value (<span class="math inline">\(\hat{y}\)</span> when all independent variables equal 0) does not mean that much.</p>
<p>Finally, the bottom half of the table includes our goodness-of-fit statistic, <span class="math inline">\(R^2\)</span>. It also includes “Adj. <span class="math inline">\(R^2\)</span>”, which is more relevant for multiple regression (discussed below). In a simple regression like this one, I want to include <span class="math inline">\(R^2\)</span> only. Note that this value is 0.00! In a simple regression like this, the one independent variable barely explains <em>any</em> of the variance in the dependent variable. We can also report 3 decimal points (<code>digits=3</code>), however, to see what the more precise value is. The table also reports the number of observations, or <em>N</em>. It reports this information as “Num. obs.” by default, but it is more common to use <em>N</em>. I can use custom “goodness-of-fit” names, and for those I want to leave as is, I can just type in <code>NA</code>, i.e., <code>custom.gof.names = c(NA, "N")</code>.</p>
<p>The table below makes the changes suggested above. I also change the order of intercept and the social media variable in the model. Researchers will often put the y-intercept at the bottom of the table since it does not matter as much for our core interpretations.</p>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(texreg)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">lm</span>(affpol <span class="sc">~</span> socialmed, <span class="at">data=</span>anes)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">htmlreg</span>(<span class="fu">list</span>(a), </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">caption =</span> <span class="st">"&lt;b&gt;The Effect of Social Media on Affective Polarization&lt;/b&gt;"</span>, </span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">center =</span> <span class="cn">TRUE</span>, </span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">digits=</span><span class="dv">3</span>,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">include.adjrs =</span> <span class="cn">FALSE</span>,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">custom.coef.names =</span> <span class="fu">c</span>(<span class="st">"Intercept"</span>, <span class="st">"Social Media Consumption"</span>), </span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">reorder.coef =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>), </span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">custom.gof.names =</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="st">"N"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;">
<caption>
<b>The Effect of Social Media on Affective Polarization</b>
</caption>
<thead>
<tr>
<th style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 1
</th>
</tr>
</thead>
<tbody>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
Social Media Consumption
</td>
<td style="padding-left: 5px;padding-right: 5px;">
4.274<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.960)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Intercept
</td>
<td style="padding-left: 5px;padding-right: 5px;">
53.715<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.546)
</td>
</tr>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.005
</td>
</tr>
<tr style="border-bottom: 2px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
N
</td>
<td style="padding-left: 5px;padding-right: 5px;">
4221
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="font-size: 0.8em;" colspan="2">
<sup>***</sup>p &lt; 0.001; <sup>**</sup>p &lt; 0.01; <sup>*</sup>p &lt; 0.05
</td>
</tr>
</tfoot>
</table>
<p>We can see that the <span class="math inline">\(R^2\)</span> is quite small, at 0.005, which means that social media consumption alone explains just 0.5% of the variance in affective polarization.</p>
</section>
<section id="the-effect-of-party-identification-on-supreme-court-approval" class="level3" data-number="8.3.2">
<h3 data-number="8.3.2" class="anchored" data-anchor-id="the-effect-of-party-identification-on-supreme-court-approval"><span class="header-section-number">8.3.2</span> The Effect of Party Identification on Supreme Court Approval</h3>
<p><a href="dataviz.html" class="quarto-xref"><span>Chapter 4</span></a> and <a href="descriptive.html" class="quarto-xref"><span>Chapter 6</span></a> analyzed the association between party identification and approval of the Supreme Court’s controversial presidential immunity ruling. We found that Republicans were more approving of the ruling than Democrats. This decision by the Court is one of many in the line conservative rulings since 2020 when President Donald Trump appointed his third justice, thus resulting in a six-justice conservative supermajority. Thus, we might also expect that Republicans are more approving of the Supreme Court generally than Democrats <span class="citation" data-cites="bartels2020 davis2026">(<a href="references.html#ref-bartels2020" role="doc-biblioref">Bartels and Johnston 2020</a>; <a href="references.html#ref-davis2026" role="doc-biblioref">Davis and Hitt 2026</a>)</span>. The ANES survey contains a 101-point thermometer rating for the Supreme Court. Below, I code that variable to remove missing data. I also summarize it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coding Supreme Court thermometer variable</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>anes <span class="ot">&lt;-</span> anes <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">sctherm =</span> <span class="fu">ifelse</span>(V242143<span class="sc">&lt;</span><span class="dv">0</span> <span class="sc">|</span> V242143<span class="sc">&gt;</span><span class="dv">100</span>, <span class="cn">NA</span>, V242143))</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>anes <span class="sc">|&gt;</span> <span class="fu">select</span>(sctherm) <span class="sc">|&gt;</span> <span class="fu">describe</span>(<span class="at">fast =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">kable</span>(<span class="at">digits=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 11%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 12%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">vars</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">range</th>
<th style="text-align: right;">skew</th>
<th style="text-align: right;">kurtosis</th>
<th style="text-align: right;">se</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">sctherm</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4870</td>
<td style="text-align: right;">48.96</td>
<td style="text-align: right;">26.54</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">-0.1</td>
<td style="text-align: right;">-0.72</td>
<td style="text-align: right;">0.38</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The mean and median are very close to each other and in the middle of the thermometer scale. The degree of skewness appears quite minimal. Before running the model, the frequency table below reminds us how party identification is coded. Understanding how the variable is coded is critical for doing interpretations using the “3 S’s” framework.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(questionr)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(anes<span class="sc">$</span>partyid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               n    % val%
[1] Str Dem 1314 23.8 24.0
[2] Wk Dem   616 11.2 11.2
[3] Ind Dem  714 12.9 13.0
[4] Ind      380  6.9  6.9
[5] Ind Rep  716 13.0 13.1
[6] Wk Rep   577 10.5 10.5
[7] Str Rep 1166 21.1 21.3
NA            38  0.7   NA</code></pre>
</div>
</div>
<p>The variable ranges from 1 to 7, where 1=Strong Democrat and 7=Strong Republican. Thus, a “1-unit increase” will be every 1 step increment from Democrat to Republican (e.g., from 1 to 2 or from 2 to 3). We can examine how a 6-unit change influences Supreme Court approval, which would represent a change from Strong Democrat (the minimum value) to Strong Republican (the maximum value).</p>
<p>The first command below estimates the multiple regression, while the second generates the output. Note that using the tips from the last simple regression, I renamed the variables and changed the order so that party is at the top followed by the intercept.</p>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>sc_sr <span class="ot">&lt;-</span> <span class="fu">lm</span>(sctherm <span class="sc">~</span> partyid, <span class="at">data=</span>anes)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">htmlreg</span>(<span class="fu">list</span>(sc_sr), </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">caption =</span> <span class="st">"&lt;b&gt;The Effect of Party on Supreme Court Approval&lt;/b&gt;"</span>, </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">center =</span> <span class="cn">TRUE</span>, </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">digits=</span><span class="dv">2</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">include.adjrs =</span> <span class="cn">FALSE</span>,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">custom.coef.names =</span> <span class="fu">c</span>(<span class="st">"Intercept"</span>, <span class="st">"Party"</span>), </span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">reorder.coef =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>), </span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">custom.gof.names =</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="st">"N"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;">
<caption>
<b>The Effect of Party on Supreme Court Approval</b>
</caption>
<thead>
<tr>
<th style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 1
</th>
</tr>
</thead>
<tbody>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
Party
</td>
<td style="padding-left: 5px;padding-right: 5px;">
6.13<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.14)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Intercept
</td>
<td style="padding-left: 5px;padding-right: 5px;">
25.19<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.64)
</td>
</tr>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.28
</td>
</tr>
<tr style="border-bottom: 2px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
N
</td>
<td style="padding-left: 5px;padding-right: 5px;">
4848
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="font-size: 0.8em;" colspan="2">
<sup>***</sup>p &lt; 0.001; <sup>**</sup>p &lt; 0.01; <sup>*</sup>p &lt; 0.05
</td>
</tr>
</tfoot>
</table>
<p>Running through the “3 S’s” framework, the results first show that party influences Supreme Court approval like we would expect: As party identification moves from Democratic to Republican, Supreme Court approval increases. Put another way, Republicans are more approving of the Court than Democrats. For every one-step increase in the Republican direction, Supreme Court approval increases by 6.13 degrees. That effect is quite large. A change from Strong Democrat (=1) to Strong Republican (=7), i.e., a 6-unit increase, results in a 36.78 degree increase in Court approval. To get that value, all I need to do is multiple <span class="math inline">\(\hat\beta_1\)</span> (6.13) by 6: <span class="math inline">\(6.13 \times 6 = 36.78\)</span>. Once again, that is a quite large effect.</p>
<p>We could also graph the predicted Supreme Court thermometer values, <span class="math inline">\(\hat{y}\)</span>, as a function of party identification. To get these seven <span class="math inline">\(\hat{y}\)</span> values, we would just plug in each party value into this equation: <span class="math inline">\(\hat{SC}_i=25.19+6.13party_i\)</span>. The <code>marginaleffects</code> package can calculate this exact output using the <code>predictions</code> command. I save this as a “tibble” (which is akin to a smaller dataset in RStudio) called “yhat.” To print out this data below and to show more than one decimal point, I simply set yhat2 to a “data frame” of the yhat tibble, which I then print out below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(marginaleffects)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>yhat <span class="ot">&lt;-</span> <span class="fu">predictions</span>(sc_sr, <span class="at">by=</span><span class="st">"partyid"</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>yhat2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(yhat) <span class="sc">|&gt;</span> <span class="fu">select</span>(partyid, estimate) <span class="sc">|&gt;</span> <span class="fu">print</span>(<span class="at">digits=</span><span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  partyid estimate
1       1    31.32
2       2    37.45
3       3    43.58
4       4    49.71
5       5    55.84
6       6    61.97
7       7    68.10</code></pre>
</div>
</div>
<p>The column for <span class="math inline">\(\hat{y}\)</span> is called “estimate.” Note that the y-intercept, <span class="math inline">\(\hat\beta_0\)</span>, in this example is actually what is called an “out-of-sample” prediction. <span class="math inline">\(\hat\beta_0\)</span> is <em>always</em> <span class="math inline">\(\hat{y}\)</span> when <em>x</em>=0, but in our ANES dataset, <em>x</em> never equals 0; party identification ranges from 1 to 7. If we coded party to range from 0 to 6 instead, then <span class="math inline">\(\hat\beta_0\)</span> would correspond with <span class="math inline">\(\hat{y}\)</span> when party=0, or strong Democrat. The yhat tibble reports additional information for inferential statistics purposes, but at this point, we are interested only in the <span class="math inline">\(\hat{y}\)</span> value associated with party.</p>
<p>Note how this table shows that for every one-step increase in party (from 1 to 2 or from 5 to 6), the predicted Supreme Court thermometer rating increases by about 6.13 degrees. The figure below directly graphs this data as a line with points for the seven <span class="math inline">\(\hat{y}\)</span> values.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>yhat <span class="sc">|&gt;</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>partyid, <span class="at">y=</span>estimate)) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"</span><span class="sc">\n</span><span class="st">Party Identification"</span>, <span class="at">y=</span><span class="st">"Predicted SC Thermometer</span><span class="sc">\n</span><span class="st">"</span>, </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">title=</span><span class="st">"Predicted Values of Supreme Court Approval</span><span class="sc">\n</span><span class="st">as a Function of Party"</span>) <span class="sc">+</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">7</span>), <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">7</span>, <span class="dv">1</span>), </span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Str Dem"</span>, <span class="st">"Wk Dem"</span>, <span class="st">"Ind Dem"</span>, <span class="st">"Ind"</span>, </span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Ind Rep"</span>, <span class="st">"Wk Rep"</span>, <span class="st">"Str Rep"</span>)) <span class="sc">+</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">80</span>), <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">20</span>, <span class="dv">80</span>, <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">12</span>, <span class="at">face=</span><span class="st">"bold"</span>, <span class="at">hjust=</span>.<span class="dv">5</span>), </span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">11</span>), </span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text  =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="linreg1_files/figure-html/yhatgraph-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="432"></p>
</figure>
</div>
</div>
</div>
<p>Researchers will sometimes report graphs like these to show both the size of the effect of <em>x</em> on <em>y</em> and also the <em>levels</em> of <em>y</em>. That is, <em>y</em> changes from <em>what to what</em>? The graph shows, for example, how a change from strong Democrat to weak Democrat increases Court approval from 31.32 to 37.45 degrees. A change from strong Democrat to strong Republican increases Court approval from 31.32 degrees all to the way up to 68.10 degrees. Once again, these are values based on the regression model and provide representations of the data based on our regression and the assumptions that go into it.</p>
</section>
</section>
<section id="multiple-regression-estimation-and-interpretation" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="multiple-regression-estimation-and-interpretation"><span class="header-section-number">8.4</span> Multiple Regression: Estimation and Interpretation</h2>
<p>Now I will examine the effect of party on Supreme Court evaluations in a <em>multiple regression</em> framework. I will give an example for how researchers think through what additional variables to control for. As discussed earlier, researchers choose which variables to control for based largely on theory (see <a href="intro.html" class="quarto-xref"><span>Chapter 2</span></a>) and past research findings. My mission is still to evaluate the effect of party on Supreme Court approval, but in multiple regression, I want to examine this effect while controlling for additional variables. The researcher manually enters these additional independent variables into the regression equation.</p>
<p>In this example, I control for five demographic variables: Education, income, sex, age, and race. By including these variables in a multiple regression model, I can examine the effect of party on Court evaluation when holding these variables constant — <em>ceteris paribus</em>.</p>
<p>The commands below create and recode new variables for these five independent variables. Education is measured as a four-category ordinal variable (varying from 1 to 4) based on level of education an individual attained. Income is also ordinal based on 28 income bands. Sex is measured using a dummy variable called “female” (1=female, 0=male). Age is measured in years, ranging from 18-80 (ANES caps age at 80, with a category of “80 or older”). Race is coded as a five-category variable for white, black, Hispanic, Asian, and other.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>anes <span class="ot">&lt;-</span> anes <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">educ =</span> <span class="fu">if_else</span>(V241465x <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="cn">NA</span>, V241465x),</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">income =</span> <span class="fu">if_else</span>(V241566x <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="cn">NA</span>, V241566x), </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">female =</span> <span class="fu">case_when</span>(V241550<span class="sc">==-</span><span class="dv">9</span> <span class="sc">~</span> <span class="cn">NA</span>,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>                            V241550<span class="sc">==</span><span class="dv">1</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>                            V241550<span class="sc">==</span><span class="dv">2</span> <span class="sc">~</span> <span class="dv">1</span>),</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">age =</span> <span class="fu">ifelse</span>(V241458x<span class="sc">&lt;</span><span class="dv">0</span>, <span class="cn">NA</span>, V241458x), </span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">race =</span> <span class="fu">ifelse</span>(V241501x<span class="sc">&lt;</span><span class="dv">0</span>, <span class="cn">NA</span>, V241501x), </span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">race =</span> <span class="fu">ifelse</span>(V241501x<span class="sc">&gt;=</span><span class="dv">5</span>, <span class="dv">5</span>, race)) <span class="sc">|&gt;</span> </span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_value_labels</span>(<span class="at">educ=</span><span class="fu">c</span>(<span class="st">"Less than HS"</span><span class="ot">=</span><span class="dv">1</span>, <span class="st">"HS"</span><span class="ot">=</span><span class="dv">2</span>, <span class="st">"Post-HS, no BA"</span><span class="ot">=</span><span class="dv">3</span>, </span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"BA"</span><span class="ot">=</span><span class="dv">4</span>, <span class="st">"Graduate degree"</span><span class="ot">=</span><span class="dv">5</span>),</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>                   <span class="at">female=</span><span class="fu">c</span>(<span class="st">"Female"</span><span class="ot">=</span><span class="dv">1</span>, <span class="st">"Male"</span><span class="ot">=</span><span class="dv">0</span>), </span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>                   <span class="at">race=</span><span class="fu">c</span>(<span class="st">"White"</span><span class="ot">=</span><span class="dv">1</span>, <span class="st">"Black"</span><span class="ot">=</span><span class="dv">2</span>, <span class="st">"Hispanic"</span><span class="ot">=</span><span class="dv">3</span>, <span class="st">"Asian"</span><span class="ot">=</span><span class="dv">4</span>,</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"Other race"</span><span class="ot">=</span><span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The command below estimates a multiple regression of the Supreme Court thermometer rating as a function of party and the five additional independent variables. As the command below shows, the researcher specifies the independent variables after the <code>~</code> and separated by a plus sign.</p>
<p>Note the use of <code>as_factor(race)</code> in the command below. Recall from <a href="dataviz.html" class="quarto-xref"><span>Chapter 4</span></a> that I treated a multicategory nominal variable like race differently than the ordinal or interval variables. While we want to control for race, we cannot simply enter it “as is” (i.e., as an ordinal variable) because it does not have a natural ordering to it, which is the hallmark of a nominal variable. Instead, for nominal variables with more than two categories (recall that race has five categories), we need to use a “dummying out” method, which shows <em>the effect of (or difference between) each race category relative to a baseline group</em>. Thus, when I specify race as a factor variable in the model, the <code>lm</code> output will automatically carry out this “dummying out” procedure. Specifically, it will include four of the five race dummy variables and leave one of the categories as the “excluded,” or “baseline,” group. Each of these dummies will equal “1” if the characteristic is present and “0” otherwise. Thus the dummy variable for “black” will equal “1” for black respondents in the survey and “0” otherwise (if one of the other categories). Finally, I note that I could also have included <code>factor(race)</code> in the <code>lm</code> command, but recall that <code>as_factor</code> uses the value labels I created (or that were preexisting) in the output.</p>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>sc_mr <span class="ot">&lt;-</span> <span class="fu">lm</span>(sctherm <span class="sc">~</span> partyid <span class="sc">+</span> female <span class="sc">+</span> educ <span class="sc">+</span> income <span class="sc">+</span> age <span class="sc">+</span> <span class="fu">as_factor</span>(race), <span class="at">data=</span>anes)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">htmlreg</span>(<span class="fu">list</span>(sc_mr), </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">caption =</span> <span class="st">"&lt;b&gt;The Effect of Party on Supreme Court Approval&lt;/b&gt;"</span>, </span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">center =</span> <span class="cn">TRUE</span>, </span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">digits=</span><span class="dv">2</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">include.rsquared =</span> <span class="cn">FALSE</span>,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">custom.gof.names =</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="st">"N"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;">
<caption>
<b>The Effect of Party on Supreme Court Approval</b>
</caption>
<thead>
<tr>
<th style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 1
</th>
</tr>
</thead>
<tbody>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
(Intercept)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
18.99<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(2.00)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
partyid
</td>
<td style="padding-left: 5px;padding-right: 5px;">
6.10<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.16)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
female
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.37
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.69)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
educ
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-1.38<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.34)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
income
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.02
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.05)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
age
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.17<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.02)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
as_factor(race)Black
</td>
<td style="padding-left: 5px;padding-right: 5px;">
6.07<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(1.29)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
as_factor(race)Hispanic
</td>
<td style="padding-left: 5px;padding-right: 5px;">
4.19<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(1.17)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
as_factor(race)Asian
</td>
<td style="padding-left: 5px;padding-right: 5px;">
8.63<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(1.89)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
as_factor(race)Other race
</td>
<td style="padding-left: 5px;padding-right: 5px;">
1.34
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(1.74)
</td>
</tr>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
Adj. R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.29
</td>
</tr>
<tr style="border-bottom: 2px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
N
</td>
<td style="padding-left: 5px;padding-right: 5px;">
4251
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="font-size: 0.8em;" colspan="2">
<sup>***</sup>p &lt; 0.001; <sup>**</sup>p &lt; 0.01; <sup>*</sup>p &lt; 0.05
</td>
</tr>
</tfoot>
</table>
<p>I once again report the model results in table form using mostly defaults from the <code>htmlreg</code> command. Here, instead of including the regular <span class="math inline">\(R^2\)</span>, I use what is known as “adjusted <span class="math inline">\(R^2\)</span>,” which is valuable for multiple regression. In multiple regression, with each additional variable included in the equation, <span class="math inline">\(R^2\)</span> will necessarily increase. Adjusted <span class="math inline">\(R^2\)</span> essentially imposes a “penalty” or an adjustment for the inclusion of additional independent variable. This adjustment incorporates the idea of how degrees of freedom imposes a sample size penalty based on the number of parameters that are estimated. Adjusted <span class="math inline">\(R^2\)</span> guards against an <span class="math inline">\(R^2\)</span> that could be inflated merely by adding more and more independent variables. In reality, adjusted <span class="math inline">\(R^2\)</span> and regular <span class="math inline">\(R^2\)</span> are usually quite similar to each other.</p>
<p>The next <code>htmlreg</code> does some of the similar housekeeping that I did in the previous section for simple regression. I give the independent variables descriptive names (as opposed to using the raw variable names), and I place the intercept at the bottom of the table instead of the top.</p>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">htmlreg</span>(<span class="fu">list</span>(sc_mr), </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">caption =</span> <span class="st">"&lt;b&gt;The Effect of Party on Supreme Court Approval&lt;/b&gt;"</span>, </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">center =</span> <span class="cn">TRUE</span>, </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">digits=</span><span class="dv">3</span>,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">include.rsquared =</span> <span class="cn">FALSE</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">custom.coef.names =</span> <span class="fu">c</span>(<span class="st">"Intercept"</span>, <span class="st">"Party"</span>, <span class="st">"Female"</span>, <span class="st">"Education"</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Income"</span>, <span class="st">"Age"</span>, <span class="st">"Race=Black"</span>, </span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Race=Hispanic"</span>, <span class="st">"Race=Asian"</span>, <span class="st">"Race=Other"</span>),</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">reorder.coef =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">10</span>, <span class="dv">1</span>),</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">custom.gof.names =</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="st">"N"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;">
<caption>
<b>The Effect of Party on Supreme Court Approval</b>
</caption>
<thead>
<tr>
<th style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 1
</th>
</tr>
</thead>
<tbody>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
Party
</td>
<td style="padding-left: 5px;padding-right: 5px;">
6.098<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.157)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Female
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.368
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.693)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Education
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-1.380<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.344)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Income
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.021
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.047)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Age
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.166<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.021)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Race=Black
</td>
<td style="padding-left: 5px;padding-right: 5px;">
6.074<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(1.285)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Race=Hispanic
</td>
<td style="padding-left: 5px;padding-right: 5px;">
4.191<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(1.173)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Race=Asian
</td>
<td style="padding-left: 5px;padding-right: 5px;">
8.627<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(1.894)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Race=Other
</td>
<td style="padding-left: 5px;padding-right: 5px;">
1.341
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(1.738)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Intercept
</td>
<td style="padding-left: 5px;padding-right: 5px;">
18.990<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(1.998)
</td>
</tr>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
Adj. R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.294
</td>
</tr>
<tr style="border-bottom: 2px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
N
</td>
<td style="padding-left: 5px;padding-right: 5px;">
4251
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="font-size: 0.8em;" colspan="2">
<sup>***</sup>p &lt; 0.001; <sup>**</sup>p &lt; 0.01; <sup>*</sup>p &lt; 0.05
</td>
</tr>
</tfoot>
</table>
<p>Before interpreting these multiple regression results, I show how one can report two regression models side by side. The code below uses <code>htmlreg</code> to report the simple regression results alongside the multiple regression results. This strategy is useful for comparing the bivariate effect of the independent variable of interest (in this case, party) with the effect from the multiple regression model when controlling for additional independent variables. The commands below implements this strategy.</p>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">htmlreg</span>(<span class="fu">list</span>(sc_sr, sc_mr), </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">caption =</span> <span class="st">"&lt;b&gt;The Effect of Party on Supreme Court Approval&lt;/b&gt;"</span>, </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">center =</span> <span class="cn">TRUE</span>, </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">digits=</span><span class="dv">3</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">include.rsquared =</span> <span class="cn">FALSE</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">custom.model.names =</span> <span class="fu">c</span>(<span class="st">"Simple&lt;br&gt;Reg."</span>, <span class="st">"Multiple&lt;br&gt;Reg."</span>),</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">custom.coef.names =</span> <span class="fu">c</span>(<span class="st">"Intercept"</span>, <span class="st">"Party"</span>, <span class="st">"Female"</span>, <span class="st">"Education"</span>,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Income"</span>, <span class="st">"Age"</span>, <span class="st">"Race=Black"</span>, </span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Race=Hispanic"</span>, <span class="st">"Race=Asian"</span>, <span class="st">"Race=Other"</span>),</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">reorder.coef =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">10</span>, <span class="dv">1</span>),</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">custom.gof.names =</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="st">"N"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;">
<caption>
<b>The Effect of Party on Supreme Court Approval</b>
</caption>
<thead>
<tr>
<th style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Simple<br>Reg.
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Multiple<br>Reg.
</th>
</tr>
</thead>
<tbody>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
Party
</td>
<td style="padding-left: 5px;padding-right: 5px;">
6.130<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
6.098<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.141)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.157)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Female
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.368
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.693)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Education
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-1.380<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.344)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Income
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.021
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.047)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Age
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.166<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.021)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Race=Black
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
6.074<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(1.285)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Race=Hispanic
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
4.191<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(1.173)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Race=Asian
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
8.627<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(1.894)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Race=Other
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
1.341
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(1.738)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Intercept
</td>
<td style="padding-left: 5px;padding-right: 5px;">
25.190<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
18.990<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.636)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(1.998)
</td>
</tr>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
Adj. R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.280
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.294
</td>
</tr>
<tr style="border-bottom: 2px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
N
</td>
<td style="padding-left: 5px;padding-right: 5px;">
4848
</td>
<td style="padding-left: 5px;padding-right: 5px;">
4251
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="font-size: 0.8em;" colspan="3">
<sup>***</sup>p &lt; 0.001; <sup>**</sup>p &lt; 0.01; <sup>*</sup>p &lt; 0.05
</td>
</tr>
</tfoot>
</table>
<p>The first core finding is that even when controlling for these additional variables, the <em>partial effect</em> of party in the multiple regression is almost exactly the same as the effect from the simple regression. That is, <em>when controlling for (or holding constant) the other independent variables</em>, Republicans are more approving of the Court than Democrats. For every one-step increase toward being a Republican, Court evaluations increase by about 6.1 degrees, <em>ceteris paribus</em>. Importantly, when we are interpreting effects from a multiple regression, we definitely want to communicate the “controlling for,” “holding constant,” or “<em>ceteris paribus</em>” language that is connected to the fact that we are estimating <em>partial</em> marginal effects. And finally, rounding out the third “S” of the “3 S’s” framework, we again see in the multiple regression that the effect of party is statistically significant at the <span class="math inline">\(\alpha=.05\)</span> level (and also at even more stringent confident levels).</p>
<p>When examining the additional independent variables, female are more approving of the Court than males, <em>ceteris paribus</em>, but the effect is very small (females are about 1/3 of a degree more approving than males) and also statistically insignificant. When controlling for the other independent variables, income has an essentially “null” and statistically insignificant effect on Court evaluations. Interestingly, holding other independent variables constant, increasing education levels <em>decrease</em> Court evaluations; that effect is statistically significant. For every one-step increase in education level (e.g., from high school to college graduate), Court evaluations decrease by about 1.4 degrees. The difference in Court evaluations between the lowest (no high school degree) and highest (graduate degree) level of education is 4.14 degrees (i.e., -1.38*3=-4.14); that is, on average, those with a graduate degree have a 4.14 degree lower evaluation than those with no high school education. Moreover, when controlling for the other independent variables, each one-year increase in age increases Court evaluations by about 1/6 of a degree; this effect is statistically significant. That effect may seem small, but recall that age ranges from 18 to 80. If we wanted to estimate the predicted increase from 18 to 80, we would multiply this partial slope by 62 (i.e., 80-18). That value is about 10.3 degrees, which is a moderately-sized effect.</p>
<p>Finally, we move to the effect of race, a nominal independent variable, on Court evaluations. By default, the <code>lm</code> command sets the lowest value as the baseline category, which in this case is 1=white. In this example, setting white as the baseline category is valuable because we often want to see in the regression results how each <em>minority</em> category compares to whites. We can easily estimate all pairwise comparisons by changing the baselines or simply taking the differences between the coefficients in the models. Just like the “female” effect is a comparison of female to male, where male is an “excluded group,” each of the race dummy variables is a comparison of the given dummy variable relative to whites, which are the excluded baseline group. Thus, we can interpret the “black” dummy variable as the following: Black respondents are about 6.1 degrees more favorable toward the Court than white respondents, holding other variables constant. That group comparison is statistically significant. It is crucial to make a <em>group comparison relative to the excluded baseline category</em>. Hispanic respondents are about 4.2 degrees more favorable toward the Court than white respondents, while Asian respondents are 8.6 degrees more favorable than whites. Each of those differences is statistically significant. While those in the “other race” category are more favorable toward the Court than whites, that difference is not statistically significant.</p>
<p>Note that in this model, the adjusted <span class="math inline">\(R^2\)</span> is a decently sized 0.29, which means that all of our independent variables explain about 29% of the variance in Supreme Court evaluations. That value is not that much greater than the <span class="math inline">\(R^2\)</span> from the simple regression, which indicates that party provides a potent explanation of Supreme Court evaluations.</p>
</section>
<section id="conclusion" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">8.5</span> Conclusion</h2>
<p>This chapter has introduced the nuts and bolts of linear regression analysis, which is the gold standard for evaluating the effects of independent variables on a dependent variable. The OLS method for regression provides an infrastructure for examining the “3 S’s” of an effect of an independent variable on a dependent variable: Its <em>sign</em>, or direction, the <em>size</em> of an effect, and whether that effect is <em>statistically significant</em>. The foundations from this chapter give readers the tools for understanding and executing more advanced model specifications and for diagnosing and correcting potential problems with one’s regression model.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-bartels2020" class="csl-entry" role="listitem">
Bartels, Brandon L., and Christopher D. Johnston. 2020. <em>Curbing the Court: Why the Public Constrains Judicial Independence</em>. New York, NY: Cambridge University Press.
</div>
<div id="ref-davis2026" class="csl-entry" role="listitem">
Davis, Nicholas T., and Matthew P. Hitt. 2026. <span>“Partisan Sorting, Fatalism, and Supreme Court Legitimacy.”</span> <em>American Journal of Political Science</em> 70 (1): 238–55. <a href="https://doi.org/10.1111/ajps.12972">https://doi.org/10.1111/ajps.12972</a>.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Note that for <em>nonlinear</em> functional forms, like those discussed in <a href="dataviz.html" class="quarto-xref"><span>Chapter 4</span></a>, the marginal effect of <em>x</em> on <em>y</em> actually changes across the regression surface.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>This derivation can be obtained via the “power rule” for derivatives. <span class="math inline">\(x_{1i}\)</span> is equivalent to <span class="math inline">\(x_{1i}^1\)</span>. In the power rule, the power, 1, comes down in front of <span class="math inline">\(\hat\beta_1\)</span> and then you subtract 1 from the power that <em>x</em> is raised to: <span class="math inline">\(1\hat\beta_1x_{1i}^0\)</span>. Any number raised to the 0th power is equal to 1. Thus, the equation simplifies to <span class="math inline">\(\hat\beta_1\)</span><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./inferential.html" class="pagination-link" aria-label="Inferential Statistics">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Inferential Statistics</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./references.html" class="pagination-link" aria-label="References">
        <span class="nav-page-text">References</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>